services:
  dogs-service:
    volumes:
      - dogs-data:/data
    build: ./dogs-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081

  cats-service:
    volumes:
      - cats-data:/data
    build: ./cats-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082

volumes:
  dogs-data:
  cats-data:
