global:
  scrape_interval: 15s

scrape_configs:
  - job_name: dogs-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - dogs-service:8081

  - job_name: cats-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - cats-service:8082