spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:dogsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8081}

services:
  cats:
    url: ${CATS_SERVICE_URL:http://cats-service:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
